//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Prefabs/Player/MovementInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MovementInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MovementInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MovementInput"",
    ""maps"": [
        {
            ""name"": ""Player_Move"",
            ""id"": ""28b95f50-df4b-406d-9e9f-1b0ad6f0474f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""329187c8-8b1f-4d27-9c7c-059df93127eb"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""b3d2aac8-3af6-4925-baec-cbc4c43e98a0"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""57c67a5b-a053-4d89-a5a8-638e6be10715"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2283ed44-c78a-4219-a3c7-e536991d7760"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4d235b96-2448-4cf5-9c2d-b9f39d83d4a0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""AD Keys"",
                    ""id"": ""ba53d7c3-2f17-4dbb-8042-cf772c57b5be"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0c3c9571-7ee6-462c-98de-66b2e15c7f93"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8941995c-cfc3-4831-ae3c-59f80d91343f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Ship_Move"",
            ""id"": ""1059cfe7-b321-4da2-89b4-ad34396009a6"",
            ""actions"": [
                {
                    ""name"": ""Movement "",
                    ""type"": ""Value"",
                    ""id"": ""b26c521d-1dd3-414d-8134-3bae9f6376dd"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""6836f3f8-4d99-45f3-9e02-b016de927750"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Vertical"",
                    ""id"": ""3cea481c-696a-4646-b3d2-54128be7a19d"",
                    ""path"": ""1DAxis(minValue=-0.5)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement "",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""2ce7a75e-9825-4fd2-a4b6-86574b44b131"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement "",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""de56824b-90cb-457b-91aa-e56efe73c4f9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement "",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Horizontal"",
                    ""id"": ""d28b327b-4e17-4b55-bfeb-989ba3f23a13"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""432fdaad-6dd5-44d9-92cf-4bd9a07c4cee"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""375f1c9a-e868-4053-aad0-80e568870b24"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Orbit_Camera"",
            ""id"": ""31d58d55-ebc9-463c-94c5-17ed107a35fc"",
            ""actions"": [
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""a7a6d1ef-261b-48f6-a4ea-eeaf8e68758e"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Adjust"",
                    ""type"": ""Button"",
                    ""id"": ""736646cc-e7af-4d96-b886-623cc5287ce8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate Horizontal"",
                    ""type"": ""Value"",
                    ""id"": ""b832a347-4f95-4fc0-ab63-a8914e20b09c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate Vertical"",
                    ""type"": ""Value"",
                    ""id"": ""63892b80-884c-4e11-b9cc-bd8681c989ca"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f357aa7e-8723-493a-9624-be9dbca11a9e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""044794e7-5a17-4637-8fb4-b04b406b5e46"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""881b6b2e-b939-40cb-819a-cdcaf3f03037"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3a1a46ac-e813-48aa-bb85-533041bb2fcf"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Adjust"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa4f37b0-7593-4bbe-873d-1a2b466228a1"",
                    ""path"": ""<Pointer>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a586d08f-7e45-4df1-b675-e132352efdb3"",
                    ""path"": ""<Pointer>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_Move
        m_Player_Move = asset.FindActionMap("Player_Move", throwIfNotFound: true);
        m_Player_Move_Movement = m_Player_Move.FindAction("Movement", throwIfNotFound: true);
        m_Player_Move_Rotate = m_Player_Move.FindAction("Rotate", throwIfNotFound: true);
        // Ship_Move
        m_Ship_Move = asset.FindActionMap("Ship_Move", throwIfNotFound: true);
        m_Ship_Move_Movement = m_Ship_Move.FindAction("Movement ", throwIfNotFound: true);
        m_Ship_Move_Rotation = m_Ship_Move.FindAction("Rotation", throwIfNotFound: true);
        // Orbit_Camera
        m_Orbit_Camera = asset.FindActionMap("Orbit_Camera", throwIfNotFound: true);
        m_Orbit_Camera_Zoom = m_Orbit_Camera.FindAction("Zoom", throwIfNotFound: true);
        m_Orbit_Camera_Adjust = m_Orbit_Camera.FindAction("Adjust", throwIfNotFound: true);
        m_Orbit_Camera_RotateHorizontal = m_Orbit_Camera.FindAction("Rotate Horizontal", throwIfNotFound: true);
        m_Orbit_Camera_RotateVertical = m_Orbit_Camera.FindAction("Rotate Vertical", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_Move
    private readonly InputActionMap m_Player_Move;
    private IPlayer_MoveActions m_Player_MoveActionsCallbackInterface;
    private readonly InputAction m_Player_Move_Movement;
    private readonly InputAction m_Player_Move_Rotate;
    public struct Player_MoveActions
    {
        private @MovementInput m_Wrapper;
        public Player_MoveActions(@MovementInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Move_Movement;
        public InputAction @Rotate => m_Wrapper.m_Player_Move_Rotate;
        public InputActionMap Get() { return m_Wrapper.m_Player_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_MoveActions set) { return set.Get(); }
        public void SetCallbacks(IPlayer_MoveActions instance)
        {
            if (m_Wrapper.m_Player_MoveActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_Player_MoveActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_Player_MoveActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_Player_MoveActionsCallbackInterface.OnMovement;
                @Rotate.started -= m_Wrapper.m_Player_MoveActionsCallbackInterface.OnRotate;
                @Rotate.performed -= m_Wrapper.m_Player_MoveActionsCallbackInterface.OnRotate;
                @Rotate.canceled -= m_Wrapper.m_Player_MoveActionsCallbackInterface.OnRotate;
            }
            m_Wrapper.m_Player_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
            }
        }
    }
    public Player_MoveActions @Player_Move => new Player_MoveActions(this);

    // Ship_Move
    private readonly InputActionMap m_Ship_Move;
    private IShip_MoveActions m_Ship_MoveActionsCallbackInterface;
    private readonly InputAction m_Ship_Move_Movement;
    private readonly InputAction m_Ship_Move_Rotation;
    public struct Ship_MoveActions
    {
        private @MovementInput m_Wrapper;
        public Ship_MoveActions(@MovementInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Ship_Move_Movement;
        public InputAction @Rotation => m_Wrapper.m_Ship_Move_Rotation;
        public InputActionMap Get() { return m_Wrapper.m_Ship_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Ship_MoveActions set) { return set.Get(); }
        public void SetCallbacks(IShip_MoveActions instance)
        {
            if (m_Wrapper.m_Ship_MoveActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_Ship_MoveActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_Ship_MoveActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_Ship_MoveActionsCallbackInterface.OnMovement;
                @Rotation.started -= m_Wrapper.m_Ship_MoveActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_Ship_MoveActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_Ship_MoveActionsCallbackInterface.OnRotation;
            }
            m_Wrapper.m_Ship_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
            }
        }
    }
    public Ship_MoveActions @Ship_Move => new Ship_MoveActions(this);

    // Orbit_Camera
    private readonly InputActionMap m_Orbit_Camera;
    private IOrbit_CameraActions m_Orbit_CameraActionsCallbackInterface;
    private readonly InputAction m_Orbit_Camera_Zoom;
    private readonly InputAction m_Orbit_Camera_Adjust;
    private readonly InputAction m_Orbit_Camera_RotateHorizontal;
    private readonly InputAction m_Orbit_Camera_RotateVertical;
    public struct Orbit_CameraActions
    {
        private @MovementInput m_Wrapper;
        public Orbit_CameraActions(@MovementInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Zoom => m_Wrapper.m_Orbit_Camera_Zoom;
        public InputAction @Adjust => m_Wrapper.m_Orbit_Camera_Adjust;
        public InputAction @RotateHorizontal => m_Wrapper.m_Orbit_Camera_RotateHorizontal;
        public InputAction @RotateVertical => m_Wrapper.m_Orbit_Camera_RotateVertical;
        public InputActionMap Get() { return m_Wrapper.m_Orbit_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Orbit_CameraActions set) { return set.Get(); }
        public void SetCallbacks(IOrbit_CameraActions instance)
        {
            if (m_Wrapper.m_Orbit_CameraActionsCallbackInterface != null)
            {
                @Zoom.started -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnZoom;
                @Adjust.started -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnAdjust;
                @Adjust.performed -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnAdjust;
                @Adjust.canceled -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnAdjust;
                @RotateHorizontal.started -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnRotateHorizontal;
                @RotateHorizontal.performed -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnRotateHorizontal;
                @RotateHorizontal.canceled -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnRotateHorizontal;
                @RotateVertical.started -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnRotateVertical;
                @RotateVertical.performed -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnRotateVertical;
                @RotateVertical.canceled -= m_Wrapper.m_Orbit_CameraActionsCallbackInterface.OnRotateVertical;
            }
            m_Wrapper.m_Orbit_CameraActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @Adjust.started += instance.OnAdjust;
                @Adjust.performed += instance.OnAdjust;
                @Adjust.canceled += instance.OnAdjust;
                @RotateHorizontal.started += instance.OnRotateHorizontal;
                @RotateHorizontal.performed += instance.OnRotateHorizontal;
                @RotateHorizontal.canceled += instance.OnRotateHorizontal;
                @RotateVertical.started += instance.OnRotateVertical;
                @RotateVertical.performed += instance.OnRotateVertical;
                @RotateVertical.canceled += instance.OnRotateVertical;
            }
        }
    }
    public Orbit_CameraActions @Orbit_Camera => new Orbit_CameraActions(this);
    public interface IPlayer_MoveActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
    }
    public interface IShip_MoveActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
    }
    public interface IOrbit_CameraActions
    {
        void OnZoom(InputAction.CallbackContext context);
        void OnAdjust(InputAction.CallbackContext context);
        void OnRotateHorizontal(InputAction.CallbackContext context);
        void OnRotateVertical(InputAction.CallbackContext context);
    }
}
